---
title: "YOUR PROJECT"
author: "YOUR NAME"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TITLE}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

## Getting started

```{r load_frap}
required_package_version <- "0.4.1"
if (packageVersion("frappp") < as.package_version(required_package_version))
  stop("version requirement not met")
```

```{r load_frap}
library(frappp)
packageVersion("frappp")
```


## Getting input files

```{r, eval = TRUE}
repoDirXML <- "~/Lab/gitlab/plprbtxml"
```

```{r, eval = FALSE}
urls <- c(
  "18" = "http://www.bundestag.de/blob/490392/3757dd46378090220e3769f2b8c1517a/pp18-data.zip",
  "17" = "http://www.bundestag.de/blob/490378/866ff042fe66d9ee46a9c955b2993dca/pp17-data.zip",
  "16" = "http://www.bundestag.de/blob/490386/680a2cc89eb71317b256bb44509ca17e/pp16-data.zip",
  "15" = "http://www.bundestag.de/blob/490394/6e9a38a40bb79abdd7fe6d74f56708ec/pp15-data.zip",
  "14" = "http://www.bundestag.de/blob/490380/1d83b7e383f9f09d88bd9e89aba07fb0/pp14-data.zip",
  "13" = "http://www.bundestag.de/blob/490388/84914a1feff6f2f4988ce352a5500845/pp13-data.zip",
  "12" = "http://www.bundestag.de/blob/490376/8775517464dccd8660eb96446d18dd26/pp12-data.zip",
  "11" = "http://www.bundestag.de/blob/490384/ad57841a599aba6faa794174e53a8797/pp11-data.zip",
  "10" = "http://www.bundestag.de/blob/490374/07ce06f666b624d37b47d2fe6e205ab4/pp10-data.zip",
  "9" = "http://www.bundestag.de/blob/490382/effcc03f3b3e157f9d8050b4a9d9d089/pp09-data.zip",
  "8" = "http://www.bundestag.de/blob/490390/dfcac024ce8e548774e16f03c36293e2/pp08-data.zip",
  "7" = "http://www.bundestag.de/blob/488222/b10bae395e887aac9ac08afbd1da62fc/pp07-data.zip",
  "6" = "http://www.bundestag.de/blob/488220/b2b4d0d49600ef852d15e4052fabce1e/pp06-data.zip",
  "5" = "http://www.bundestag.de/blob/488218/bfba1a02d1090efc873f9a60f318a162/pp05-data.zip",
  "4" = "http://www.bundestag.de/blob/488216/3b20f8dd5efad2cafa3fb0b6df24cbb9/pp04-data.zip",
  "3" = "http://www.bundestag.de/blob/487970/1c737594587745b399e84bc30f049d69/pp03-data.zip",
  "2" = "http://www.bundestag.de/blob/487968/5792895a5cf4ab51ed94c77157297031/pp02-data.zip",
  "1" = "http://www.bundestag.de/blob/487966/4078f01fb3198dc3cee8945d6db3b231/pp01-data.zip"
)

# for (url in urls){
#   targetFile <- file.path(repoDirXML, basename(url))
#   print(targetFile)
#   download.file(url = url, destfile = targetFile)
#   cat(
#     sprintf("%s\n", paste(url, Sys.time(), sep = "\t")),
#     file = file.path(repoDir, "README"),
#     append = TRUE
#     )
# }

# for (url in urls){
#   message("... unzipping ", basename(url))
#   zipfile <- file.path(repoDir, basename(url))
#   unzip(zipfile = zipfile, exdir = repoDir)
# }
#
# for (url in urls) file.remove(file.path(repoDir, basename(url)))
```


## Define parser

```{r}
library(R6)
library(xml2)
library(magrittr)
library(pbapply)
```

```{r}
GermaParlParser <- R6Class(
  
  "GermaParlParser",
  inherit = PlenaryProtocolParser,
  
  public = list(
    
    xmldoc = NULL, # class 'xml_document' from packabe 'xml2'
    download_report = NULL, # a data.frame
    
    initialize = function(download_report_file){
      
      self$download_report <- read.table(file = download_report_file, stringsAsFactors = FALSE)
      rownames(self$download_report) <- gsub(
        "^.*?/pp(\\d+)-data.zip$", "\\1", self$download_report[,1]
        ) %>% as.integer() %>% as.character()
      self$download_report <- self$download_report[as.integer(rownames(self$download_report)),]
      colnames(self$download_report) <- c("url", "date", "time")
      
      self$xpath <- teiXpath

      invisible(self)
    },
    
    read_file = function(filename, id){
      self$id <- id
      self$xmldoc <- xml2::read_xml(x = filename)
      self$txt <- xml2::xml_find_first(x = self$xmldoc, xpath = "/DOKUMENT/TEXT") %>%
        xml_text() %>%
        strsplit(x = ., split = "\\n") %>% 
        unlist()
      invisible(self)
    },
    
    get_metadata = function(download_report){
      lp <- xml2::xml_find_first(x = self$xmldoc, xpath = "/DOKUMENT/WAHLPERIODE") %>%
        xml_text() %>%
        as.integer()
      no <- xml2::xml_find_first(x = self$xmldoc, xpath = "/DOKUMENT/NR") %>%
        xml_text() %>%
        gsub("^\\d+/(\\d+)$", "\\1", .) %>%
        as.integer()
      date <- xml2::xml_find_first(x = self$xmldoc, xpath = "/DOKUMENT/DATUM") %>%
        xml_text()
        as.Date(date, format = "%d.%m.%Y")
      list(
        legislativePeriod = lp,
        sessionNo = no,
        date = date,
        url = self$download_report[as.character(lp), "url"],
        retrievalDate = as.Date(self$download_report[as.character(lp), "date"]),
        package = "frappp",
        version = packageVersion("frappp"),
        birthday = Sys.Date()
        )
    },

    xmlify = function(){
    }
  )
)
```





## Configure the parser

We need to construct the regex for parliamentarians in advance ... 

```{r}
source("~/Lab/gitlab/GermaParl/data-raw/plprbtxml/parliamentary_groups_regex.R")
pg_regex_2 <- paste(sprintf("\\s*%s\\s*", unname(pg_regex)), collapse = "|")
mp_regex <- sprintf("^\\s*(?!\\()(?!(Vizepräsident|Präsident))(?!.*?Parl\\.\\s+Staatssekretär)(.+?)\\s*\\((%s)\\)(|\\s*\\(von\\s.*?mit Beifall be\\s?grüßt\\))\\s*:\\s*(.*?)$", pg_regex_2)
```


```{r}
GPP <- GermaParlParser$new(download_report_file = file.path(repoDirXML, "README"))

GPP$speaker_regex <- list(
  
  pres = list(
    regex = "^\\s*(?!\\()(P|Vizep|Altersp)räsident(|in)\\s+(?!des\\sSenats)([^!,]*?):\\s*(.*)$",
    fn = function(x){
      data.frame(
        who = x[,4],
        parliamentary_group = if (nrow(x) >= 1) "NA" else character(),
        role = if (nrow(x) >= 1) "presidency" else character(),
        position = if (nrow(x) >= 1) sprintf("%sräsident%s", x[,2], x[,3]) else character(),
        text = x[,5],
        stringsAsFactors = FALSE
      )
    }
  ),
  
  mp = list(
    regex = mp_regex,
    fn = function(x){
      data.frame(
        who = x[,3],
        parliamentary_group = x[,4],
        role = if (nrow(x) >= 1) "mp" else character(),
        position = if (nrow(x) >= 1) "NA" else character(),
        text = x[,6],
        stringsAsFactors = FALSE
      )
    }
  ),
  
  gov = c(
    regex = "^\\s*(?!\\()([^!]+?),\\s(Bundeskanzler|Bundesminister|Staatsminister\\s+(?!\\()|Staatsministerin\\s+(?!\\()|Staatssekretär|Parl\\.\\s+Staatssekretär|Beauftragter?\\sder\\sBundesregierung)([^!]*?)(|\\s*\\(vo[nm]\\s.*?mit Beifall be\\s?grüßt\\)):\\s*(.*?)$",
    fn = function(x) data.frame(
      who = x[,2],
      parliamentary_group = if (nrow(x) >= 1) "NA" else character(),
      role = if (nrow(x) >= 1) "government" else character(),
      position = sprintf("%s%s", x[,3], x[,4]),
      text = x[,6],
      stringsAsFactors = FALSE
    )
  ),
  
  state_a = c(
    regex="^\\s*(?!\\()(Präsident\\sdes\\Senats|Präsidentin\\sdes\\sSenats|Ministerpräsident|Ministerpräsidentin|Staatsminister|Staatsministerin)\\s+(.*?)\\s+(\\(.*?\\))(|\\s*\\(vo[nm]\\s.*?mit Beifall be\\s?grüßt\\)):(.*?)$",
    fn = function(x) data.frame(
      who = x[,3],
      parliamentary_group = if (nrow(x) >= 1) "NA" else character(),
      role = if (nrow(x) >= 1) "federal_council" else character(),
      position = x[,4],
      text = x[,6],
      stringsAsFactors = FALSE
    )
  ),
  
  state_b = c(
    regex = "^\\s*(?!\\()(.*?),\\s*(Minister|Ministerin|Staatsminister|Staatsministerin|Ministerpräsident|Ministerpräsidentin)\\s*(\\(.*?\\))\\s*(|\\s*\\(vo[nm]\\s.*?mit Beifall be\\s?grüßt\\)):(.*?)$",
    fn = function(x) data.frame(
      who = x[,2],
      parliamentary_group = if (nrow(x) >= 1) "NA" else character(),
      role = if (nrow(x) >= 1) "federal_council" else character(),
      position = x[,3],
      text = x[,6],
      stringsAsFactors = FALSE
    )
  ),
  
  comm = list(
    regex = "^\\s*(?!\\()(.*),\\s+Wehrbeauftragte(r|)\\sdes\\sDeutschen\\sBundestag(e|)s:(.*?)$",
    fn = function(x) data.frame(
      who = x[,2],  
      parliamentary_group = if (nrow(x) >= 1) "NA" else character(),
      role = if (nrow(x) >= 1) "parliamentary_commissioner" else character(),
      position = if (nrow(x) >= 1) "Wehrbeauftragter des Deutschen Bundestags" else character(),
      text = x[,4],
      stringsAsFactors = FALSE
    )
  )
  
)


GPP$speaker_mismatch <- character()

GPP$agenda_item_regex <- c(any = "^XXXXX$")
GPP$agenda_item_types <- c(any = "debate")

GPP$stage_regex <- c(interjection = "^\\s*\\(.*?\\)\\s*$")
GPP$stage_match_n_lines <- 2L
```





```{r processing_multiple_docs, message = FALSE}
xmldir <- "/Users/blaette/Lab/gitlab/plprbtxml"
teidir <- "/Users/blaette/Lab/tmp/NewGermaParlTEI"
files <- Sys.glob(paths = sprintf("%s/*.xml", xmldir))
files <- file.path(xmldir, "01001.xml")
# files <- head(files, n = 200L)

y <- pblapply(
  files,
  function(xmlfile){
    # message(xmlfile)
    GPP$read_file(filename = xmlfile, id = basename(xmlfile))
    GPP$metadata <- GPP$get_metadata()
    GPP$make_header()
    GPP$split_by_speakers()
    GPP$detect_stage_regex_matches()
    GPP$reconstruct_paragraphs(exclude = "pres")
    GPP$make_body()
    writeLines(
      text = as.character(GPP$xml),
      con = file.path(teidir, basename(xmlfile))
    )
    GPP$chunk_data
  },
  cl = 3L
  )
df <- data.frame(do.call(rbind, y))
```

Reduktion dieser Tabelle (718653 Zeilen / 7 Spalten) auf 'unique' Sprecher.

```{r}
df_min <- plyr::ddply(
  .data = df, .variables = c("who", "parliamentary_group", "role"),
  .fun = function(x) x[1,], .progress = "text"
  )
```

