# BÜNDNIS[\\s\xa0]90\\/DIE\\sGRÜNEN

c(
  "KPD" = "KPD",
  "SPD" = "SPD",
  "BP" = "BP",
  "CDU/CSU" = "CDU\\s*[/'\"%-,;:!\\s]\\s*CSU",
  "CDU" = "CDU",
  "CSU" = "CSU",
  "DP" = "DP",
  "DP/DPB" = "DP\\s*/\\s*DPB",
  "DP/FVP" = "DP\\s*/\\s*FVP",
  "GB/BHE" = "GB\\s*/\\s*BHE",
  "F.D.P." = "F\\s*\\.?\\s*D[\\.:]?\\s*P[\\.,:]?",
  "FDP" = "FD'?P",
  "FVP" = "\\s*FVP\\s",
  "Bündnis 90/Die Grünen" = "Bündnis\\s*90\\s*/\\s*Die\\s+Grünen",
  "Bündnis 90/GRÜNE" = "Bündnis\\s*90\\s*/\\s*GR[ÜU]NE",
  "BÜNDNIS 90/GRÜNE" = "BÜNDNIS\\s*90\\s*/\\s*GRÜNE",
  "BÜNDNIS 90/DIE GRÜNEN" = "BÜND*NI*S\\s*90\\s*/\\s*D[I1]E\\s*GRÜN+EN",
  "GRÜNE" = "GRÜNE",
  "Bündnis 90/DIE GRÜNEN" = "Bündnis\\s*90\\s*/\\s*DIE\\s*GRÜNEN",
  "DIE GRÜNEN" = "DIE\\s*GRÜNEN",
  "BÜNDNIS 90/Die GRÜNEN" = "BÜND*NIS\\s*90\\s*/\\s*Die\\s*GRÜNEN",
  "GRÜNE" = "GR[Üü]NE",
  "PDS" = "PDS",
  "Die LINKE" = "Die\\s+LINKE",
  "DIE LINKE" = "DIE\\s+LINKE",
  "Die Linke" = "Die\\s+Linke",
  "Gruppe der PDS" = "Gr?uppe\\s+der\\s+PDS",
  "fraktionslos" = "[fF]rakt*ions*[il]os",
  "parteilos" = "[pP]arteilos",
  "WAV" = "WAV",
  "Z" = "Z"
)
