c(
  "Gerade gestern fand ich zufällig, aber ganz aktuell ein Interview mit Dr. Horst Waffenschmidt",
  "Das macht deutlich, welches Verwirrspiel in der Koalition bei diesem Thema herrscht. Man gewinnt gelegentlich den Eindruck",
  "Die Kollegin Haßelmann hat schon auf einige Punkte hingewiesen. Sie wissen doch, was Sie an Erhöhungen und Aufschlägen bei den Hebesätzen durchsetzen müssten, wenn Sie das alles aufkommensneutral gestalten wollen. Ich verstehe das nicht. Da weiß wieder die rechte Hand nicht, was die linke Hand tut. Wenn Sie das so machen, wie Sie es jetzt planen, müssen Sie die Mehrwertsteuer deutlich erhöhen, auf bis zu 25 Prozent. Das hat Herr Zimmermann vom DIW gerade vorgeschlagen. Herr Kampeter",
  "Wie sah es damit in Ihren Ministerien während Ihrer Regierungsverantwortung aus?   Ich habe mir die Zahlen einmal genauer angeschaut. Die Frau Kollegin Alpers hatte eine entsprechende schriftliche Anfrage gestellt. Für die Jahre 2008 und 2009 hat die Bundesregierung mitgeteilt: Auswärtiges Amt",
  "Vizepräsidentin Michaela Geiger: Der Zusammenhang mit der ursprünglichen Frage ist nur noch schwer zu erkennen. Aber bitte schön, Herr Staatssekretär",
  "Abschließen möchte ich mit einem Zitat des rheinland-pfälzischen Infrastrukturministers Roger Lewenz",
  "Bereits zum dritten Mal hat der Bundesrat den Versuch unternommen, eine dringend notwendige Veränderung der",
  "Nun gebe ich das Wort dem Abgeordneten Peter Basten. Franz Peter Basten",
  "-- hier vermerkt das Protokoll:",
  "Dann verzeichnet der Sitzungsbericht",
  "Mandela hat gesagt",
  "Karzai hat die vordringlichen Aufgaben seiner Regierung sehr plastisch beschrieben",
  "Putin hat mit seiner gelenkten Demokratie eine neue Regierungsform etabliert und ein Paradoxon zur Leitlinie gemacht",
  "Obama hat in seiner Rede vor dem ghanaischen Parlament gesagt",
  "Milosevic muß wissen",
  "Barsani hat zu mir gesagt",
  "Meine Damen und Herren",
  "Kollege Pfaff hat gesagt",
  "- Natürlich",
  "Der persönliche Beauftragte für den Konvent",
  "Herr Koch-Weser",
  "Lieber Herr Gerhardt",
  "Ich habe, wie in der Haushaltsdebatte bereits angekündigt",
  "Am 22. Januar dieses Jahres hat Kollege Koschyk",
  "Liebe Kolleginnen und Kollegen",
  "Bundesministerium der Finanzen",
  "Bundesministerium für Arbeit und Soziales",
  "Auch Ihre Vermutung",
  "-- hier vermerkt das Protokoll",
  "sein! - Dirk Niebel",
  "DIE GRÜNEN - Friedrich Merz",
  "-- hier vermerkt das Protokoll: \"Rudolf Bindig",
  "sein! - Dirk Niebel",
  "DIE GRÜNEN - Friedrich Merz",
  "Meine Damen und Herren",
  "Kollege Pfaff hat gesagt",
  "Fischer",
  "- Natürlich",
  "DIE GRÜNEN - Joseph Fischer",
  "Der persönliche Beauftragte für den Konvent",
  "Lieber Herr Gerhardt",
  "Ich habe, wie in der Haushaltsdebatte bereits angekündigt",
  "Am 22. Januar dieses Jahres hat Kollege Koschyk",
  "Liebe Kolleginnen und Kollegen",
  "Bundesministerium der Finanzen",
  "Bundesministerium für Arbeit und Soziales",
  "Auch Ihre Vermutung",
  "Kanzlerin Merkel",
  "Liebe Kolleginnen und Kollegen",
  "Herr Koch-Weser",
  "Herr Jürgen Trittin",
  "SPD – Dr. Guido Westerwelle",
  "zustimmen? – Dr. Ilja Seifert",
  "[SPD] – Jörg van Essen",
  "Obama weiß auch",
  "Sarkozy und ich waren von Beginn an davon überzeugt",
  "hat es noch einmal deutlich gesagt –",
  "Clinton hat zu Recht gesagt",
  "aus dem Bericht zweitens",
  "Als Sie vor 13 Jahren, Herr Bundeskanzler Kohl",
  "Widmung? – Dr. Guido Westerwelle",
  "ich Peter Kemper",
  # "LINKE) – Dr. Max Stadler",
  "Frage! - Dr. Uwe Küster",
  "Dr. Antje Vollmer Berichterstattung",
  "Hans-Ulrich Klose Berichterstattung",
  "Herr Hüppe"
)
